# Generated by Django 5.1.4 on 2024-12-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('1', 'Child'), ('0', 'Master')], max_length=5)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=255)),
                ('is_angle', models.BooleanField(default=False)),
                ('angle_totp', models.CharField(max_length=255, null=True)),
                ('angle_api_key', models.CharField(max_length=255, null=True)),
                ('angle_seceret_key', models.CharField(max_length=255, null=True)),
                ('is_zerodha', models.BooleanField(default=False)),
                ('zerodha_totp', models.CharField(max_length=255, null=True)),
                ('zerodha_api_key', models.CharField(max_length=255, null=True)),
                ('zerodha_seceret_key', models.CharField(max_length=255, null=True)),
                ('is_aliceblue', models.BooleanField(default=False)),
                ('aliceblue_totp', models.CharField(max_length=255, null=True)),
                ('aliceblue_api_key', models.CharField(max_length=255, null=True)),
                ('aliceblue_seceret_key', models.CharField(max_length=255, null=True)),
                ('referal_code', models.CharField(blank=True, max_length=64)),
                ('child_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'master',
                'ordering': ['-created'],
            },
        ),
    ]
